/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  DEFAULT_SETTINGS: () => DEFAULT_SETTINGS,
  YuqueStylePlugin: () => YuqueStylePlugin,
  default: () => YuqueStylePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/reader.ts
var import_obsidian = require("obsidian");
var ReaderEnhancer = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.lastKey = "";
  }
  register() {
    const refresh = (0, import_obsidian.debounce)(() => this.refresh(), 400);
    const { workspace } = this.plugin.app;
    this.plugin.registerEvent(workspace.on("active-leaf-change", () => {
      refresh();
    }));
    this.plugin.registerEvent(workspace.on("layout-change", () => {
      refresh();
    }));
    this.plugin.registerMarkdownPostProcessor(() => {
      refresh();
    });
    this.plugin.registerInterval(window.setInterval(() => this.refresh(), 1500));
  }
  /** force = true 时无视缓存强制重新装饰 */
  refresh(force = false) {
    var _a, _b;
    if (force) this.lastKey = "";
    const view = this.plugin.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!view) return;
    const s = this.plugin.settings;
    const previewEl = view.contentEl.querySelector(".markdown-preview-view");
    const sourceEl = view.contentEl.querySelector(".markdown-source-view");
    const mode = view.getMode();
    const key = `${(_b = (_a = view.file) == null ? void 0 : _a.path) != null ? _b : ""}|${mode}`;
    const applyHeadingNum = (el, isPreview) => {
      el.classList.toggle("yuque-heading-num", s.reader && s.headingNumbers);
      let hasH1;
      if (isPreview) {
        hasH1 = Array.from(el.querySelectorAll("h1")).some(
          (h) => !h.closest(".yuque-doc-header") && !h.closest(".yuque-outline")
        );
      } else {
        hasH1 = el.querySelector(".HyperMD-header-1") !== null;
      }
      el.classList.toggle("yuque-heading-num-no-h1", s.reader && s.headingNumbers && !hasH1);
    };
    if (previewEl) applyHeadingNum(previewEl, true);
    if (sourceEl) applyHeadingNum(sourceEl, false);
    if (!s.reader || mode !== "preview" || !previewEl) {
      if (previewEl) this.cleanup(previewEl);
      this.lastKey = "";
      return;
    }
    if (key === this.lastKey) return;
    this.lastKey = key;
    this.cleanup(previewEl);
    previewEl.classList.add("yuque-reader");
    if (s.headingNumbers) {
      previewEl.classList.add("yuque-heading-num");
      const hasH1 = Array.from(previewEl.querySelectorAll("h1")).some(
        (h) => !h.closest(".yuque-doc-header") && !h.closest(".yuque-outline")
      );
      if (!hasH1) previewEl.classList.add("yuque-heading-num-no-h1");
    }
    if (s.showDocHeader) this.injectHeader(view, previewEl);
    if (s.showOutline) this.injectOutline(previewEl);
  }
  cleanup(container) {
    container.classList.remove("yuque-reader");
    container.classList.remove("yuque-heading-num");
    container.classList.remove("yuque-heading-num-no-h1");
    container.querySelectorAll(".yuque-doc-header, .yuque-outline").forEach((n) => n.remove());
  }
  injectHeader(view, container) {
    var _a, _b, _c;
    const file = view.file;
    if (!file) return;
    const cache = this.plugin.app.metadataCache.getFileCache(file);
    const header = createEl("div", { cls: "yuque-doc-header" });
    header.createEl("h1", {
      cls: "yuque-doc-title",
      text: String((_b = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.title) != null ? _b : file.basename)
    });
    const meta = createEl("div", { cls: "yuque-doc-meta" });
    void this.plugin.app.vault.cachedRead(file).then((content) => {
      const plain = content.replace(/```[\s\S]*?```/g, " ").replace(/[#>*_`~|\[\]()!-]/g, " ");
      const words = plain.replace(/\s+/g, "").length;
      meta.createSpan({ text: `${words} \u5B57` });
      if (this.plugin.settings.showReadingTime) {
        const minutes = Math.max(1, Math.round(words / 400));
        meta.createSpan({ text: `\u7EA6 ${minutes} \u5206\u949F\u8BFB\u5B8C` });
      }
      meta.createSpan({
        text: `\u521B\u5EFA\u4E8E ${window.moment(file.stat.ctime).format("YYYY-MM-DD")}`
      });
    });
    const tags = (_c = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _c.tags;
    if (Array.isArray(tags)) {
      for (const t of tags.slice(0, 8)) {
        meta.createSpan({ cls: "yuque-tag", text: String(t) });
      }
    }
    header.appendChild(meta);
    container.insertBefore(header, container.firstChild);
  }
  injectOutline(container) {
    var _a;
    const headings = Array.from(
      container.querySelectorAll("h1, h2, h3")
    ).filter((h) => !h.closest(".yuque-doc-header") && !h.closest(".yuque-outline"));
    if (headings.length === 0) return;
    const outline = createEl("div", { cls: "yuque-outline" });
    outline.createEl("div", { cls: "yuque-outline-title", text: "\u672C\u6587\u76EE\u5F55" });
    const list = outline.createEl("div", { cls: "yuque-outline-list" });
    for (const h of headings) {
      const item = list.createEl("a", {
        cls: `yuque-outline-item yuque-outline-${h.tagName.toLowerCase()}`,
        text: (_a = h.textContent) != null ? _a : ""
      });
      item.addEventListener("click", (e) => {
        e.preventDefault();
        h.scrollIntoView({ behavior: "smooth", block: "start" });
      });
    }
    container.appendChild(outline);
  }
  toggleOutline() {
    const outline = document.querySelector(
      ".markdown-preview-view .yuque-outline"
    );
    if (outline) {
      outline.classList.toggle("yuque-outline-hidden");
    } else {
      new import_obsidian.Notice("\u5F53\u524D\u6CA1\u6709\u53EF\u7528\u7684\u6587\u6863\u76EE\u5F55");
    }
  }
};

// src/slash.ts
var import_obsidian2 = require("obsidian");
var ITEMS = [
  { name: "\u6807\u9898 1", hint: "\u5927\u53F7\u7AE0\u8282\u6807\u9898", keywords: ["h1", "bt", "biaoti"], insert: "# ", cursorBack: 0 },
  { name: "\u6807\u9898 2", hint: "\u4E2D\u53F7\u7AE0\u8282\u6807\u9898", keywords: ["h2"], insert: "## ", cursorBack: 0 },
  { name: "\u6807\u9898 3", hint: "\u5C0F\u53F7\u7AE0\u8282\u6807\u9898", keywords: ["h3"], insert: "### ", cursorBack: 0 },
  { name: "\u6807\u9898 4", hint: "\u66F4\u5C0F\u53F7\u6807\u9898", keywords: ["h4"], insert: "#### ", cursorBack: 0 },
  { name: "\u5F85\u529E\u6E05\u5355", hint: "\u53EF\u52FE\u9009\u7684\u4EFB\u52A1\u5217\u8868", keywords: ["todo", "daiban", "db", "task"], insert: "- [ ] ", cursorBack: 0 },
  { name: "\u65E0\u5E8F\u5217\u8868", hint: "\u9879\u76EE\u7B26\u53F7\u5217\u8868", keywords: ["list", "liebiao", "ul"], insert: "- ", cursorBack: 0 },
  { name: "\u6709\u5E8F\u5217\u8868", hint: "\u7F16\u53F7\u5217\u8868", keywords: ["ol", "order"], insert: "1. ", cursorBack: 0 },
  { name: "\u5F15\u7528\u5757", hint: "\u5F15\u7528\u4E00\u6BB5\u6587\u5B57", keywords: ["quote", "yinyong", "yy"], insert: "> ", cursorBack: 0 },
  {
    name: "\u5361\u7247\u5757",
    hint: "\u8BED\u96C0\u5F0F\u6807\u6CE8\u5361\u7247\uFF08\u84DD\u8272\u4FBF\u7B7E\uFF09",
    keywords: ["card", "kapian", "kp", "callout", "note"],
    insert: "> [!note] \u5361\u7247\u6807\u9898\n> \u5728\u8FD9\u91CC\u586B\u5199\u5361\u7247\u5185\u5BB9\u3002",
    cursorBack: 8
  },
  {
    name: "\u63D0\u793A\u5361\u7247",
    hint: "\u7EFF\u8272\u63D0\u793A\u6807\u6CE8",
    keywords: ["tip", "tishi", "ts"],
    insert: "> [!tip] \u63D0\u793A\n> \u5728\u8FD9\u91CC\u586B\u5199\u63D0\u793A\u5185\u5BB9\u3002",
    cursorBack: 8
  },
  {
    name: "\u8B66\u544A\u5361\u7247",
    hint: "\u6A59\u9EC4\u8272\u8B66\u544A\u6807\u6CE8",
    keywords: ["warning", "warn", "jinggao", "jg"],
    insert: "> [!warning] \u8B66\u544A\n> \u5728\u8FD9\u91CC\u586B\u5199\u8B66\u544A\u5185\u5BB9\u3002",
    cursorBack: 8
  },
  {
    name: "\u8868\u683C",
    hint: "\u63D2\u5165 3x3 \u8868\u683C",
    keywords: ["table", "biaoge", "bg"],
    insert: "| \u5217\u540D | \u5217\u540D | \u5217\u540D |\n| --- | --- | --- |\n| \u5185\u5BB9 | \u5185\u5BB9 | \u5185\u5BB9 |\n| \u5185\u5BB9 | \u5185\u5BB9 | \u5185\u5BB9 |\n",
    cursorBack: 0
  },
  {
    name: "\u4EE3\u7801\u5757",
    hint: "\u591A\u884C\u4EE3\u7801\uFF08\u4E0D\u5E26\u8BED\u8A00\u6807\u6CE8\uFF09",
    keywords: ["code", "daima", "dm", "codeblock"],
    insert: "```\n\n```",
    cursorBack: 4
  },
  {
    name: "Python \u4EE3\u7801\u5757",
    hint: "\u5E26\u8BED\u8A00\u6807\u6CE8\u7684\u4EE3\u7801\u5757",
    keywords: ["py", "python", "\u8BED\u8A00", "\u4EE3\u7801"],
    insert: "```python\n\n```",
    cursorBack: 4
  },
  {
    name: "JavaScript \u4EE3\u7801\u5757",
    hint: "\u5E26\u8BED\u8A00\u6807\u6CE8\u7684\u4EE3\u7801\u5757",
    keywords: ["js", "javascript", "\u8BED\u8A00", "\u4EE3\u7801"],
    insert: "```javascript\n\n```",
    cursorBack: 4
  },
  {
    name: "TypeScript \u4EE3\u7801\u5757",
    hint: "\u5E26\u8BED\u8A00\u6807\u6CE8\u7684\u4EE3\u7801\u5757",
    keywords: ["ts", "typescript", "\u8BED\u8A00", "\u4EE3\u7801"],
    insert: "```typescript\n\n```",
    cursorBack: 4
  },
  {
    name: "Java \u4EE3\u7801\u5757",
    hint: "\u5E26\u8BED\u8A00\u6807\u6CE8\u7684\u4EE3\u7801\u5757",
    keywords: ["java", "\u8BED\u8A00", "\u4EE3\u7801"],
    insert: "```java\n\n```",
    cursorBack: 4
  },
  {
    name: "Bash \u4EE3\u7801\u5757",
    hint: "Shell / \u547D\u4EE4\u884C",
    keywords: ["bash", "sh", "shell", "linux", "\u8BED\u8A00", "\u4EE3\u7801"],
    insert: "```bash\n\n```",
    cursorBack: 4
  },
  {
    name: "PowerShell \u4EE3\u7801\u5757",
    hint: "Windows \u547D\u4EE4\u884C / \u811A\u672C",
    keywords: ["powershell", "ps", "ps1", "pwsh", "windows", "\u8BED\u8A00", "\u4EE3\u7801"],
    insert: "```powershell\n\n```",
    cursorBack: 4
  },
  {
    name: "SQL \u4EE3\u7801\u5757",
    hint: "\u6570\u636E\u5E93\u67E5\u8BE2",
    keywords: ["sql", "mysql", "\u8BED\u8A00", "\u4EE3\u7801"],
    insert: "```sql\n\n```",
    cursorBack: 4
  },
  {
    name: "JSON \u4EE3\u7801\u5757",
    hint: "JSON \u6570\u636E",
    keywords: ["json", "\u8BED\u8A00", "\u4EE3\u7801"],
    insert: "```json\n\n```",
    cursorBack: 4
  },
  {
    name: "YAML \u4EE3\u7801\u5757",
    hint: "\u914D\u7F6E\u6587\u4EF6",
    keywords: ["yaml", "yml", "\u8BED\u8A00", "\u4EE3\u7801"],
    insert: "```yaml\n\n```",
    cursorBack: 4
  },
  {
    name: "HTML \u4EE3\u7801\u5757",
    hint: "\u7F51\u9875\u6807\u8BB0",
    keywords: ["html", "\u8BED\u8A00", "\u4EE3\u7801"],
    insert: "```html\n\n```",
    cursorBack: 4
  },
  {
    name: "CSS \u4EE3\u7801\u5757",
    hint: "\u6837\u5F0F\u8868",
    keywords: ["css", "\u8BED\u8A00", "\u4EE3\u7801"],
    insert: "```css\n\n```",
    cursorBack: 4
  },
  {
    name: "Go \u4EE3\u7801\u5757",
    hint: "\u5E26\u8BED\u8A00\u6807\u6CE8\u7684\u4EE3\u7801\u5757",
    keywords: ["go", "golang", "\u8BED\u8A00", "\u4EE3\u7801"],
    insert: "```go\n\n```",
    cursorBack: 4
  },
  {
    name: "C++ \u4EE3\u7801\u5757",
    hint: "\u5E26\u8BED\u8A00\u6807\u6CE8\u7684\u4EE3\u7801\u5757",
    keywords: ["cpp", "c++", "c", "\u8BED\u8A00", "\u4EE3\u7801"],
    insert: "```cpp\n\n```",
    cursorBack: 4
  },
  {
    name: "\u5206\u5272\u7EBF",
    hint: "\u6C34\u5E73\u5206\u9694\u7EBF",
    keywords: ["hr", "fgx", "line"],
    insert: "\n---\n",
    cursorBack: 0
  },
  {
    name: "\u6570\u5B66\u516C\u5F0F",
    hint: "\u5757\u7EA7 LaTeX \u516C\u5F0F",
    keywords: ["math", "formula", "gongshi", "gs", "latex"],
    insert: "$$\n\n$$",
    cursorBack: 3
  },
  {
    name: "\u4ECA\u65E5\u65E5\u671F",
    hint: "\u63D2\u5165\u4ECA\u5929\u7684\u65E5\u671F",
    keywords: ["date", "riqi", "rq", "today"],
    insert: window.moment().format("YYYY-MM-DD"),
    cursorBack: 0
  }
];
var YuqueSlashSuggest = class extends import_obsidian2.EditorSuggest {
  constructor(plugin) {
    super(plugin.app);
    this.plugin = plugin;
  }
  /** 输入 "/"（行首或空格后）时触发菜单 */
  onTrigger(cursor, editor, _file) {
    if (!this.plugin.settings.slashMenu) return null;
    const line = editor.getLine(cursor.line);
    const before = line.slice(0, cursor.ch);
    const m = before.match(/(?:^|\s)\/([^/\s]*)$/);
    if (!m) return null;
    return {
      start: { line: cursor.line, ch: cursor.ch - m[1].length - 1 },
      end: { line: cursor.line, ch: cursor.ch },
      query: m[1]
    };
  }
  getSuggestions(context) {
    const q = context.query.toLowerCase();
    if (!q) return ITEMS;
    return ITEMS.filter((it) => {
      if (it.name.toLowerCase().includes(q)) return true;
      if (it.hint.toLowerCase().includes(q)) return true;
      return it.keywords.some((k) => k.toLowerCase().includes(q) || k.toLowerCase().startsWith(q));
    });
  }
  renderSuggestion(item, el) {
    const row = el.createEl("div", { cls: "yuque-slash-row" });
    row.createEl("span", { cls: "yuque-slash-name", text: item.name });
    row.createEl("span", { cls: "yuque-slash-hint", text: item.hint });
  }
  selectSuggestion(item, evt) {
    this.onChooseSuggestion(item, evt);
    this.close();
  }
  onChooseSuggestion(item, _evt) {
    const ctx = this.context;
    if (!ctx) return;
    const editor = ctx.editor;
    const startOffset = editor.posToOffset(ctx.start);
    editor.replaceRange(item.insert, ctx.start, ctx.end);
    const cursorOffset = startOffset + item.insert.length - item.cursorBack;
    editor.setCursor(editor.offsetToPos(cursorOffset));
  }
};

// src/toolbar.ts
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
function wrap(view, mark) {
  const sel = view.state.selection.main;
  if (sel.empty) return;
  const text = view.state.sliceDoc(sel.from, sel.to);
  view.dispatch({
    changes: { from: sel.from, to: sel.to, insert: `${mark}${text}${mark}` },
    selection: import_state.EditorSelection.range(sel.from + mark.length, sel.to + mark.length)
  });
}
function toggleLinePrefix(view, prefix) {
  const { state } = view;
  const sel = state.selection.main;
  const firstLine = state.doc.lineAt(sel.from);
  const lastLine = state.doc.lineAt(sel.to);
  const changes = [];
  for (let n = firstLine.number; n <= lastLine.number; n++) {
    const line = state.doc.line(n);
    if (line.text.startsWith(prefix)) {
      changes.push({ from: line.from, to: line.from + prefix.length, insert: "" });
    } else {
      changes.push({ from: line.from, to: line.from, insert: prefix });
    }
  }
  view.dispatch({ changes });
}
var ACTIONS = [
  { label: "B", title: "\u52A0\u7C97", apply: (v) => wrap(v, "**") },
  { label: "I", title: "\u659C\u4F53", apply: (v) => wrap(v, "*") },
  { label: "S", title: "\u5220\u9664\u7EBF", apply: (v) => wrap(v, "~~") },
  { label: "\u9AD8", title: "\u9AD8\u4EAE", apply: (v) => wrap(v, "==") },
  { label: "</>", title: "\u884C\u5185\u4EE3\u7801", apply: (v) => wrap(v, "`") },
  { label: "H1", title: "\u6807\u9898 1", apply: (v) => toggleLinePrefix(v, "# ") },
  { label: "H2", title: "\u6807\u9898 2", apply: (v) => toggleLinePrefix(v, "## ") },
  { label: "H3", title: "\u6807\u9898 3", apply: (v) => toggleLinePrefix(v, "### ") },
  { label: "H4", title: "\u6807\u9898 4", apply: (v) => toggleLinePrefix(v, "#### ") },
  { label: "\u5F15", title: "\u5F15\u7528", apply: (v) => toggleLinePrefix(v, "> ") },
  { label: "\u529E", title: "\u5F85\u529E", apply: (v) => toggleLinePrefix(v, "- [ ] ") }
];
var TOOLBAR_HEIGHT = 40;
var TOOLBAR_GAP = 8;
var YuqueToolbar = class {
  constructor(view, isEnabled) {
    this.view = view;
    this.isEnabled = isEnabled;
    this.onScroll = () => this.reposition();
    this.host = view.scrollDOM;
    this.host.style.position = "relative";
    this.dom = createEl("div", { cls: "yuque-toolbar" });
    this.dom.addEventListener("mousedown", (e) => e.preventDefault());
    for (const action of ACTIONS) {
      const btn = this.dom.createEl("button", {
        cls: "yuque-toolbar-btn",
        text: action.label,
        attr: { "aria-label": action.title, title: action.title }
      });
      btn.addEventListener("mousedown", (e) => {
        e.preventDefault();
        action.apply(this.view);
        this.view.focus();
        this.reposition();
      });
    }
    this.dom.style.display = "none";
    this.host.appendChild(this.dom);
    this.host.addEventListener("scroll", this.onScroll, { passive: true });
  }
  update(update) {
    if (update.selectionSet || update.docChanged || update.focusChanged || update.viewportChanged) {
      this.reposition();
    }
  }
  hide() {
    this.dom.style.display = "none";
  }
  reposition() {
    try {
      const sel = this.view.state.selection.main;
      if (!this.isEnabled() || sel.empty || !this.view.hasFocus) {
        this.hide();
        return;
      }
      const start = this.view.coordsAtPos(sel.from);
      const end = this.view.coordsAtPos(sel.to);
      if (!start || !end) {
        this.hide();
        return;
      }
      const hostRect = this.host.getBoundingClientRect();
      const selectionTop = Math.min(start.top, end.top);
      const selectionCenterX = (Math.min(start.left, end.left) + Math.max(start.right, end.right)) / 2;
      this.dom.style.display = "flex";
      const top = selectionTop - hostRect.top + this.host.scrollTop - TOOLBAR_HEIGHT - TOOLBAR_GAP;
      const rawLeft = selectionCenterX - hostRect.left + this.host.scrollLeft - this.dom.offsetWidth / 2;
      const left = Math.min(
        Math.max(rawLeft, 4),
        Math.max(this.host.clientWidth - this.dom.offsetWidth - 4, 4)
      );
      this.dom.style.top = `${Math.max(top, 4)}px`;
      this.dom.style.left = `${left}px`;
    } catch (e) {
      this.hide();
    }
  }
  destroy() {
    this.host.removeEventListener("scroll", this.onScroll);
    this.dom.remove();
  }
};
function buildYuqueToolbar(isEnabled) {
  return import_view.ViewPlugin.fromClass(
    class extends YuqueToolbar {
      constructor(view) {
        super(view, isEnabled);
      }
    }
  );
}

// src/yuque/api.ts
var import_obsidian3 = require("obsidian");
var BASE = "https://www.yuque.com/api/v2";
function nsPath(namespace) {
  return String(namespace).split("/").map(encodeURIComponent).join("/");
}
var sleep = (ms) => new Promise((r) => setTimeout(r, ms));
var YuqueApiError = class extends Error {
  constructor(message, status) {
    super(message);
    this.status = status;
    this.name = "YuqueApiError";
  }
};
var YuqueApi = class {
  constructor(token) {
    this.token = token;
    this.lastReqAt = 0;
  }
  setToken(token) {
    this.token = token;
  }
  async throttle() {
    const minGap = 400;
    const wait = this.lastReqAt + minGap - Date.now();
    if (wait > 0) await sleep(wait);
    this.lastReqAt = Date.now();
  }
  /**
   * requestUrl 对非 2xx 默认直接抛异常（"Request failed, status xxx"），
   * 必须设置 throw: false 才能拿到响应自行判断状态码。
   */
  async rawRequest(path) {
    return await (0, import_obsidian3.requestUrl)({
      url: BASE + path,
      method: "GET",
      headers: {
        "X-Auth-Token": this.token,
        "User-Agent": "obsidian-yuque-style"
      },
      throw: false
    });
  }
  async requestJson(path, onRetry) {
    var _a, _b, _c, _d;
    const maxAttempts = 4;
    const backoffMs = [5e3, 15e3, 3e4];
    for (let attempt = 1; ; attempt++) {
      await this.throttle();
      let res;
      try {
        res = await this.rawRequest(path);
      } catch (e) {
        throw new YuqueApiError(`\u8BF7\u6C42\u5F02\u5E38\uFF08${path}\uFF09\uFF1A${e.message}`, 0);
      }
      if (res.status === 429) {
        if (attempt >= maxAttempts) {
          throw new YuqueApiError(
            `\u8BED\u96C0 API \u9650\u6D41\uFF08429\uFF0C${path}\uFF09\uFF1A\u5DF2\u81EA\u52A8\u91CD\u8BD5 ${maxAttempts - 1} \u6B21\u4ECD\u5931\u8D25\u3002\u8BED\u96C0\u5BF9 API \u8C03\u7528\u6709\u5C0F\u65F6\u7EA7\u914D\u989D\uFF08\u514D\u8D39\u8D26\u6237\u8F83\u4F4E\uFF09\uFF0C\u8BF7\u7B49\u5F85 10-60 \u5206\u949F\u540E\u518D\u540C\u6B65`,
            429
          );
        }
        const wait = (_a = backoffMs[attempt - 1]) != null ? _a : 3e4;
        onRetry == null ? void 0 : onRetry(Math.round(wait / 1e3), attempt);
        await sleep(wait);
        this.lastReqAt = 0;
        continue;
      }
      if (res.status === 401) {
        throw new YuqueApiError("Token \u65E0\u6548\u6216\u5DF2\u8FC7\u671F\uFF0C\u8BF7\u5230\u8BED\u96C0\u300C\u8BBE\u7F6E \u2192 Token\u300D\u91CD\u65B0\u751F\u6210", 401);
      }
      if (res.status === 404) {
        throw new YuqueApiError(
          `\u63A5\u53E3\u4E0D\u5B58\u5728\u6216\u65E0\u6743\u8BBF\u95EE\uFF08404\uFF09\uFF1A${path}\u3002\u82E5\u4E3A\u77E5\u8BC6\u5E93\u5217\u8868\u8BF7\u6C42\uFF0C\u8BF7\u786E\u8BA4\u63D2\u4EF6\u5DF2\u66F4\u65B0\u5230\u6700\u65B0\u7248\u672C`,
          404
        );
      }
      if (res.status >= 400) {
        let msg = `HTTP ${res.status}`;
        try {
          msg = (_c = (_b = res.json) == null ? void 0 : _b.message) != null ? _c : msg;
        } catch (e) {
        }
        throw new YuqueApiError(`\u8BED\u96C0 API \u8BF7\u6C42\u5931\u8D25\uFF08${path}\uFF09\uFF1A${msg}`, res.status);
      }
      return (_d = res.json) == null ? void 0 : _d.data;
    }
  }
  /** 当前用户信息（用于验证 Token） */
  async getUser() {
    return this.requestJson("/user");
  }
  /** 我的知识库列表（自动翻页）。语雀 v2 无 /repos 端点，须用 /users/:login/repos */
  async getRepos() {
    const user = await this.getUser();
    const login = (user == null ? void 0 : user.login) || (user == null ? void 0 : user.id);
    if (!login) throw new YuqueApiError("\u65E0\u6CD5\u83B7\u53D6\u5F53\u524D\u7528\u6237\u4FE1\u606F\uFF08Token \u65E0\u6548\uFF1F\uFF09", 401);
    const out = [];
    let offset = 0;
    for (; ; ) {
      const page = await this.requestJson(
        `/users/${encodeURIComponent(String(login))}/repos?offset=${offset}&limit=100`
      );
      if (!Array.isArray(page) || page.length === 0) break;
      out.push(...page);
      if (page.length < 100) break;
      offset += 100;
    }
    return out;
  }
  /**
   * 知识库文档列表（自动翻页）。
   * 兼容两种 namespace：若标准 namespace 取到 0 篇但 TOC 非空，可能是团队库（namespace
   * 以 group login 开头但返回的 namespace 字段缺失/不一致），此时按 TOC 里记录的
   * namespace 重试一次。
   */
  async getDocList(namespace) {
    let list = await this.getDocListOnce(namespace);
    if (list.length > 0) return list;
    try {
      const toc = await this.getTocOnce(namespace);
      if (toc.length === 0) return list;
      for (const node of toc) {
        if (node.url) {
          const m = node.url.match(/^\/([^/]+)\/([^/]+)/);
          if (m && m[1] && m[1] !== namespace) {
            const retry = await this.getDocListOnce(m[1]);
            if (retry.length > 0) return retry;
          }
        }
      }
      return list;
    } catch (e) {
      return list;
    }
  }
  /** 单次获取文档列表（无探测重试，节省配额；探测逻辑由调用方决定） */
  async getDocListOnce(namespace) {
    const out = [];
    let offset = 0;
    for (; ; ) {
      const page = await this.requestJson(
        `/repos/${nsPath(namespace)}/docs?offset=${offset}&limit=100`
      );
      if (!Array.isArray(page) || page.length === 0) break;
      out.push(...page);
      if (page.length < 100) break;
      offset += 100;
    }
    return out;
  }
  /** 目录树（TOC 可能有内容但 docs 列表为空——文档未加入目录的情况） */
  async getTocOnce(namespace) {
    const data = await this.requestJson(`/repos/${nsPath(namespace)}/toc`);
    return Array.isArray(data) ? data : [];
  }
  /** 文档详情（body 为 Lake 格式） */
  async getDoc(namespace, slug) {
    return this.requestJson(
      `/repos/${nsPath(namespace)}/docs/${encodeURIComponent(slug)}`
    );
  }
  /** 知识库目录树 */
  async getToc(namespace, onRetry) {
    const data = await this.requestJson(`/repos/${nsPath(namespace)}/toc`, onRetry);
    return Array.isArray(data) ? data : [];
  }
  /** 诊断用：原始请求，返回状态码与响应体文本（不做任何解析兜底） */
  async getRaw(path) {
    var _a;
    await this.throttle();
    let res;
    try {
      res = await (0, import_obsidian3.requestUrl)({
        url: BASE + path,
        method: "GET",
        headers: {
          "X-Auth-Token": this.token,
          "User-Agent": "obsidian-yuque-style"
        },
        throw: false
      });
    } catch (e) {
      return { status: 0, text: `\u7F51\u7EDC\u5F02\u5E38\uFF1A${e.message}` };
    }
    let text = "";
    try {
      text = typeof res.text === "string" ? res.text : JSON.stringify((_a = res.json) != null ? _a : null);
    } catch (e) {
      text = "<\u65E0\u6CD5\u8BFB\u53D6\u54CD\u5E94\u4F53>";
    }
    return { status: res.status, text };
  }
  /** 下载二进制资源（图片/附件） */
  async downloadBinary(url) {
    await this.throttle();
    const res = await (0, import_obsidian3.requestUrl)({ url, method: "GET", throw: false });
    if (res.status >= 400) throw new YuqueApiError(`\u8D44\u6E90\u4E0B\u8F7D\u5931\u8D25\uFF08${res.status}\uFF09\uFF1A${url}`, res.status);
    return res.arrayBuffer;
  }
};

// src/yuque/sync.ts
var import_obsidian4 = require("obsidian");

// src/yuque/lake.ts
var CALLOUT_STATUS_MAP = {
  default: "note",
  info: "note",
  success: "tip",
  warning: "warning",
  danger: "danger",
  error: "danger"
};
var BLOCK_CARD_NAMES = /* @__PURE__ */ new Set([
  "image",
  "codeblock",
  "hr",
  "math",
  "callout",
  "table",
  "lakesheet",
  "laketable",
  "lakeboard",
  "board",
  "video",
  "taskList"
]);
function decodeCardValue(el) {
  const v = el.getAttribute("value");
  if (!v) return null;
  let encoded = v;
  if (encoded.startsWith("data:")) encoded = encoded.slice(5);
  try {
    return JSON.parse(decodeURIComponent(encoded));
  } catch (e) {
    try {
      return JSON.parse(encoded);
    } catch (e2) {
      return null;
    }
  }
}
function escapeMdText(text) {
  return text.replace(/\u00a0/g, " ");
}
function escapeTableCell(text) {
  return text.replace(/\|/g, "\\|").replace(/\n/g, "<br>");
}
var LakeConverter = class _LakeConverter {
  constructor() {
    this.warnings = /* @__PURE__ */ new Set();
    this.parser = new DOMParser();
  }
  convert(lake) {
    let src = lake.replace(/\x00/g, "");
    src = src.replace(/<!doctype[^>]*>/gi, "");
    src = src.replace(/<meta[^>]*>/gi, "");
    const doc = this.parser.parseFromString(`<body>${src}</body>`, "text/html");
    const blocks = this.convertBlocks(Array.from(doc.body.childNodes), 0);
    let md = blocks.join("\n\n");
    md = md.replace(/\n{3,}/g, "\n\n").trim() + "\n";
    return { markdown: md, warnings: Array.from(this.warnings) };
  }
  // ---------- 块级 ----------
  convertBlocks(nodes, baseIndent) {
    const out = [];
    for (const node of Array.from(nodes)) {
      if (node.nodeType === Node.TEXT_NODE) {
        const t = escapeMdText(node.textContent || "").trim();
        if (t) out.push(t);
        continue;
      }
      if (node.nodeType !== Node.ELEMENT_NODE) continue;
      const block = this.convertElement(node, baseIndent);
      if (block && block.trim()) out.push(block);
    }
    return out;
  }
  convertElement(el, baseIndent) {
    var _a;
    const tag = el.tagName.toLowerCase();
    switch (tag) {
      case "h1":
      case "h2":
      case "h3":
      case "h4":
      case "h5":
      case "h6":
      case "ne-h1":
      case "ne-h2":
      case "ne-h3":
      case "ne-h4":
      case "ne-h5":
      case "ne-h6": {
        const level = Number(tag.replace(/\D/g, ""));
        return `${"#".repeat(level)} ${this.convertInline(el)}`;
      }
      case "p":
      case "ne-p": {
        const text = this.convertInline(el);
        if (!text.trim()) return null;
        return text;
      }
      case "blockquote":
      case "ne-quote": {
        const blocks = this.convertBlocks(el.childNodes, 0);
        if (blocks.length === 0) return null;
        return blocks.join("\n\n").split("\n").map((l) => `> ${l}`.trimEnd()).join("\n");
      }
      case "ul":
      case "ol":
      case "ne-uli":
      case "ne-oli":
        return this.convertList(el, tag === "ol" || tag === "ne-oli", 1);
      case "li":
      case "ne-li":
        return this.convertListItems([el], false, 1).join("\n");
      case "pre": {
        const code = (_a = el.textContent) != null ? _a : "";
        const lang = this.detectCodeLanguage(el);
        return this.fenceCode(code, lang);
      }
      case "ne-codeblock":
        return this.convertNeCodeblock(el);
      case "table":
      case "ne-table":
        return this.convertTable(el);
      case "hr":
      case "ne-hr":
        return "---";
      case "ne-callout":
        return this.convertNeCallout(el);
      case "card":
        return this.convertCard(el, baseIndent);
      case "div":
      case "section":
      case "span":
      case "ne-span":
      case "ne-paragraph":
        return this.convertBlocks(el.childNodes, baseIndent).join("\n\n") || null;
      case "img": {
        const src = el.getAttribute("src") || "";
        if (src) return `![${el.getAttribute("alt") || ""}](${src})`;
        return null;
      }
      default: {
        const inner = this.convertBlocks(el.childNodes, baseIndent).join("\n\n");
        if (inner.trim()) return inner;
        if (tag.startsWith("ne-")) {
          this.warnings.add(`\u672A\u652F\u6301\u7684\u8BED\u96C0\u5757\uFF1A${tag}`);
          return null;
        }
        return null;
      }
    }
  }
  convertList(listEl, ordered, level) {
    const items = Array.from(listEl.children).filter(
      (c) => c.tagName.toLowerCase() === "li" || c.tagName.toLowerCase() === "ne-li"
    );
    if (items.length === 0) {
      const blocks = this.convertBlocks(listEl.childNodes, 0);
      return blocks.join("\n");
    }
    return this.convertListItems(items, ordered, level).join("\n");
  }
  convertListItems(items, ordered, level) {
    const lines = [];
    let index = 1;
    for (const li of items) {
      const indent = "  ".repeat(Math.max(0, level - 1));
      const checkCard = li.querySelector('card[name="checkbox"]');
      const checkedAttr = li.getAttribute("data-lake-checked");
      let marker;
      if (checkCard) {
        const v = decodeCardValue(checkCard) || {};
        const checked = v.checked === true || v.checked === "true";
        marker = `- [${checked ? "x" : " "}] `;
        if (checkCard.parentNode) checkCard.parentNode.removeChild(checkCard);
      } else if (checkedAttr !== null) {
        marker = `- [${checkedAttr === "true" ? "x" : " "}] `;
      } else {
        marker = ordered ? `${index++}. ` : "- ";
      }
      const hasBlockChild = Array.from(li.children).some((c) => {
        const t = c.tagName.toLowerCase();
        if (t === "card") {
          if (c.getAttribute("type") === "inline") return false;
          const name = c.getAttribute("name") || "";
          return BLOCK_CARD_NAMES.has(name);
        }
        return /^(p|ne-p|ul|ol|ne-uli|ne-oli|blockquote|ne-quote|table|ne-table|h[1-6]|ne-h[1-6]|pre|ne-codeblock)$/.test(t);
      });
      if (!hasBlockChild) {
        const text = this.convertInline(li).replace(/\s+/g, " ").trim();
        if (text) lines.push(`${indent}${marker}${text}`);
        continue;
      }
      const blocks = this.convertBlocks(li.childNodes, 0);
      if (blocks.length === 0) continue;
      const first = blocks.shift();
      lines.push(`${indent}${marker}${first.replace(/\n+/g, " ")}`);
      for (const rest of blocks) {
        lines.push(
          rest.split("\n").map((l) => `${indent}  ${l}`.trimEnd()).join("\n")
        );
      }
    }
    return lines;
  }
  detectCodeLanguage(el) {
    const cls = el.getAttribute("class") || "";
    const m = cls.match(/language-([\w+#-]+)/);
    if (m) return m[1];
    return "";
  }
  fenceCode(code, lang) {
    const backticks = "```";
    const clean = code.replace(/\n+$/, "");
    if (clean.includes(backticks)) return `${backticks}${lang}
${clean}
${backticks}`;
    return `${backticks}${lang}
${clean}
${backticks}`;
  }
  /** 新版 ne-codeblock：<ne-codeblock><ne-codeblock-language>py</ne-codeblock-language><ne-codeblock-content>...</ne-codeblock-content></ne-codeblock> */
  convertNeCodeblock(el) {
    var _a, _b;
    let lang = el.getAttribute("data-lake-language") || "";
    const langEl = el.querySelector("ne-codeblock-language");
    if (!lang && langEl) lang = (langEl.textContent || "").trim();
    let code = "";
    const contentEl = el.querySelector("ne-codeblock-content");
    if (contentEl) {
      code = Array.from(contentEl.querySelectorAll("p, ne-p, div")).map((p) => {
        var _a2;
        return (_a2 = p.textContent) != null ? _a2 : "";
      }).join("\n");
      if (!code) code = (_a = contentEl.textContent) != null ? _a : "";
    } else {
      const clone = el.cloneNode(true);
      clone.querySelectorAll("ne-codeblock-language").forEach((n) => n.remove());
      code = (_b = clone.textContent) != null ? _b : "";
    }
    if (lang) lang = lang.replace(/^lang-/, "");
    return this.fenceCode(code, lang);
  }
  convertNeCallout(el) {
    const status = (el.getAttribute("status") || "info").toLowerCase();
    const type = CALLOUT_STATUS_MAP[status] || "note";
    const titleEl = el.querySelector("ne-callout-title, ne-callout-head");
    let title = "";
    let contentEl = el;
    if (titleEl) {
      title = this.convertInline(titleEl).trim();
      const contentWrap = el.querySelector("ne-callout-content");
      contentEl = contentWrap || el;
    }
    const blocks = [];
    for (const child of Array.from(contentEl.children)) {
      const tag = child.tagName.toLowerCase();
      if (tag === "ne-callout-title" || tag === "ne-callout-head") continue;
      const b = this.convertElement(child, 0);
      if (b && b.trim()) blocks.push(b);
    }
    if (blocks.length === 0) {
      const text = escapeMdText(contentEl.textContent || "").trim();
      if (text) blocks.push(text);
    }
    const head = `> [!${type}]${title ? ` ${title}` : ""}`;
    const body = blocks.join("\n\n").split("\n").map((l) => `> ${l}`.trimEnd()).join("\n");
    return `${head}
${body}`;
  }
  convertTable(el) {
    const rows = [];
    const rowEls = Array.from(el.querySelectorAll("tr, ne-table-row"));
    const seen = /* @__PURE__ */ new Set();
    for (const row of rowEls) {
      if (seen.has(row)) continue;
      seen.add(row);
      const cellEls = Array.from(
        row.querySelectorAll(":scope > td, :scope > th, :scope > ne-table-cell")
      );
      const header = rowEls.indexOf(row) === 0;
      rows.push({
        cells: cellEls.map((c) => escapeTableCell(this.convertInline(c).trim())),
        header
      });
    }
    if (rows.length === 0) {
      this.warnings.add("\u8868\u683C\u8F6C\u6362\u5931\u8D25\uFF08\u672A\u627E\u5230\u884C\uFF09");
      return null;
    }
    const width = Math.max(...rows.map((r) => r.cells.length));
    const norm = rows.map((r) => {
      const cells = [...r.cells];
      while (cells.length < width) cells.push("");
      return cells;
    });
    const lines = [];
    lines.push(`| ${norm[0].join(" | ")} |`);
    lines.push(`| ${Array(width).fill("---").join(" | ")} |`);
    for (const r of norm.slice(1)) lines.push(`| ${r.join(" | ")} |`);
    return lines.join("\n");
  }
  // ---------- 卡片（<card name="..." value="data:...">） ----------
  convertCard(el, baseIndent) {
    var _a, _b, _c, _d, _e, _f;
    const name = el.getAttribute("name") || "";
    const isInline = el.getAttribute("type") === "inline";
    const value = decodeCardValue(el) || {};
    switch (name) {
      case "image": {
        const src = value.src || value.url || "";
        if (!src) {
          this.warnings.add("\u56FE\u7247\u5361\u7247\u7F3A\u5C11 src");
          return null;
        }
        const alt = (value.name || value.alt || "").replace(/[\r\n]/g, " ");
        return `![${alt}](${src})`;
      }
      case "localdoc":
      case "file": {
        const src = value.src || value.url || "";
        const fname = value.name || "\u9644\u4EF6";
        return src ? `[${fname}](${src})` : `[${fname}]`;
      }
      case "bookmarklink": {
        const url = value.url || value.href || "";
        const title = value.title || value.url || "\u94FE\u63A5";
        return `[${title}](${url})`;
      }
      case "yuque":
      case "yuqueinline": {
        const url = value.src || value.url || "";
        const title = value.title || value.name || url;
        return url ? `[${title}](${url})` : null;
      }
      case "hr":
        return "---";
      case "codeblock": {
        let code = (_a = value.code) != null ? _a : "";
        if (!code) {
          code = Array.from(el.querySelectorAll("p, ne-p, div")).map((p) => {
            var _a2;
            return (_a2 = p.textContent) != null ? _a2 : "";
          }).join("\n");
          if (!code) code = (_b = el.textContent) != null ? _b : "";
        }
        const lang = (value.language || value.code_lang || "").replace(/^lang-/, "");
        return this.fenceCode(code, lang);
      }
      case "math":
      case "inlineMath": {
        const latex = (_f = (_e = (_d = (_c = value.latex) != null ? _c : value.code) != null ? _d : value.tex) != null ? _e : el.textContent) != null ? _f : "";
        const clean = String(latex).trim();
        if (!clean) return null;
        return isInline || name === "inlineMath" ? `$${clean}$` : `$$
${clean}
$$`;
      }
      case "callout": {
        const status = String(value.status || "info").toLowerCase();
        const type = CALLOUT_STATUS_MAP[status] || "note";
        const title = String(value.title || "").trim();
        const blocks = [];
        const html = value.html || value.content || value.contents;
        if (typeof html === "string" && html) {
          const sub = new _LakeConverter().convert(html);
          for (const w of sub.warnings) this.warnings.add(w);
          blocks.push(sub.markdown.trim());
        } else if (Array.isArray(html)) {
          for (const part of html) {
            const sub = new _LakeConverter().convert(String(part));
            blocks.push(sub.markdown.trim());
          }
        } else {
          const inner = this.convertBlocks(el.childNodes, 0).join("\n\n");
          if (inner.trim()) blocks.push(inner);
        }
        const head = `> [!${type}]${title ? ` ${title}` : ""}`;
        const body = blocks.join("\n\n").split("\n").map((l) => `> ${l}`.trimEnd()).join("\n");
        return `${head}
${body}`;
      }
      case "checkbox": {
        const checked = value.checked === true || value.checked === "true";
        return `- [${checked ? "x" : " "}] `;
      }
      case "taskList": {
        const html = value.html || value.content;
        if (typeof html === "string" && html) {
          return new _LakeConverter().convert(html).markdown.trim();
        }
        if (Array.isArray(value.items)) {
          return value.items.map((it) => `- [${it.checked ? "x" : " "}] ${it.title || ""}`).join("\n");
        }
        return null;
      }
      case "table":
      case "lakesheet": {
        const html = value.html || value.content;
        if (typeof html === "string" && /<t[dhr]|<table/i.test(html)) {
          const sub = new _LakeConverter().convert(html).markdown.trim();
          if (sub) return sub;
        }
        this.warnings.add("\u8868\u683C\uFF08lakesheet\uFF09\u6682\u65E0\u6CD5\u5B8C\u6574\u8FD8\u539F\uFF0C\u5DF2\u4FDD\u7559\u8BED\u96C0\u94FE\u63A5\u5360\u4F4D");
        return `> [!warning] \u8868\u683C
> \u6B64\u5904\u4E3A\u8BED\u96C0\u9AD8\u7EA7\u8868\u683C\uFF0C\u8BF7\u5728\u8BED\u96C0\u4E2D\u67E5\u770B\u3002`;
      }
      case "laketable": {
        this.warnings.add("\u6570\u636E\u8868\uFF08laketable\uFF09\u4EC5\u8BB0\u5F55\u5360\u4F4D");
        return `> [!warning] \u6570\u636E\u8868
> \u6B64\u5904\u4E3A\u8BED\u96C0\u6570\u636E\u8868\uFF0C\u8BF7\u5728\u8BED\u96C0\u4E2D\u67E5\u770B\u3002`;
      }
      case "lakeboard":
      case "board": {
        this.warnings.add("\u753B\u677F\uFF08lakeboard\uFF09\u4EC5\u8BB0\u5F55\u5360\u4F4D");
        return `> [!warning] \u753B\u677F
> \u6B64\u5904\u4E3A\u8BED\u96C0\u753B\u677F/\u601D\u7EF4\u5BFC\u56FE\uFF0C\u8BF7\u5728\u8BED\u96C0\u4E2D\u67E5\u770B\u3002`;
      }
      case "video": {
        const url = value.src || value.url || "";
        return url ? `[\u{1F4F9} \u89C6\u9891](${url})` : `> [!warning] \u89C6\u9891
> \u8BED\u96C0\u89C6\u9891\uFF0C\u8BF7\u5728\u8BED\u96C0\u4E2D\u67E5\u770B\u3002`;
      }
      case "mention": {
        const who = value.name || value.login || "";
        return who ? `@${who}` : null;
      }
      case "br":
        return "\n";
      default: {
        const text = escapeMdText(el.textContent || "").trim();
        if (text) return text;
        this.warnings.add(`\u672A\u652F\u6301\u7684\u8BED\u96C0\u5361\u7247\uFF1A${name}`);
        return `> [!warning] \u672A\u652F\u6301\u5185\u5BB9
> \u8BED\u96C0\u5361\u7247\u300C${name}\u300D\u6682\u4E0D\u652F\u6301\u5728\u6B64\u5C55\u793A\uFF0C\u8BF7\u5728\u8BED\u96C0\u4E2D\u67E5\u770B\u3002`;
      }
    }
  }
  // ---------- 行内 ----------
  convertInline(el) {
    let out = "";
    for (const node of Array.from(el.childNodes)) {
      if (node.nodeType === Node.TEXT_NODE) {
        out += escapeMdText(node.textContent || "");
        continue;
      }
      if (node.nodeType !== Node.ELEMENT_NODE) continue;
      const child = node;
      const tag = child.tagName.toLowerCase();
      switch (tag) {
        case "strong":
        case "b":
        case "ne-strong":
          out += `**${this.convertInline(child).trim() || ""}**`;
          break;
        case "em":
        case "i":
        case "ne-em":
          out += `*${this.convertInline(child).trim() || ""}*`;
          break;
        case "u":
        case "ne-u":
          out += `<u>${this.convertInline(child)}</u>`;
          break;
        case "s":
        case "del":
        case "strike":
        case "ne-strike":
          out += `~~${this.convertInline(child).trim() || ""}~~`;
          break;
        case "code":
        case "ne-code": {
          const text = child.textContent || "";
          out += text.includes("`") ? `\`\`${text}\`\`` : `\`${text}\``;
          break;
        }
        case "a":
        case "ne-link": {
          const href = child.getAttribute("href") || "";
          const text = this.convertInline(child).trim() || href;
          out += href ? `[${text}](${href})` : text;
          break;
        }
        case "br":
          out += "\n";
          break;
        case "mark":
          out += `==${this.convertInline(child)}==`;
          break;
        case "span":
        case "ne-span":
        case "div":
        case "font": {
          const style = (child.getAttribute("style") || "").toLowerCase();
          if (style.includes("background-color") || style.includes("background:")) {
            out += `==${this.convertInline(child)}==`;
          } else {
            out += this.convertInline(child);
          }
          break;
        }
        case "card": {
          const md = this.convertCard(child, 0);
          out += md || "";
          break;
        }
        case "ne-image":
        case "img": {
          const card = child.querySelector("card[name='image']");
          if (card) {
            out += this.convertCard(card, 0) || "";
          } else {
            const src = child.getAttribute("src") || "";
            out += src ? `![](${src})` : this.convertInline(child);
          }
          break;
        }
        default:
          out += this.convertInline(child);
      }
    }
    return out;
  }
};
function lakeToMarkdown(lake) {
  if (!lake || !lake.trim()) return { markdown: "", warnings: [] };
  return new LakeConverter().convert(lake);
}
function isLakeBody(body) {
  if (!body) return false;
  if (/^\s*<!doctype\s+lake/i.test(body)) return true;
  if (/<card[\s>]/i.test(body)) return true;
  if (/<ne-[a-z]/i.test(body)) return true;
  if (/<(p|div|h[1-6]|table|ul|ol|blockquote)[\s>]/i.test(body)) {
    const mdChars = "#>*-.|`";
    return !body.split("\n").some((line) => {
      const t = line.trimStart();
      return t === "" || mdChars.includes(t[0]) || /^\d+\.\s/.test(t);
    });
  }
  return false;
}
function isDefaultColor(style) {
  return /rgb\(\s*0\s*,\s*0\s*,\s*0\s*\)/i.test(style) || !/color/i.test(style);
}
function cleanMarkdownBody(md) {
  const warnings = [];
  let out = md;
  for (let i = 0; i < 5; i++) {
    const next = out.replace(
      /<font([^>]*)>([\s\S]*?)<\/font>/gi,
      (_m, attrs, inner) => {
        if (isDefaultColor(attrs)) return inner;
        const colorMatch = attrs.match(/color:\s*([^;"']+)/i);
        const color = colorMatch ? colorMatch[1].trim() : "";
        return color ? `<span style="color:${color}">${inner}</span>` : inner;
      }
    );
    if (next === out) break;
    out = next;
  }
  out = out.replace(/<font[^>]*>/gi, "").replace(/<\/font>/gi, "");
  out = out.replace(/<br\s*\/?>/gi, "\n");
  out = out.replace(/\n{3,}/g, "\n\n").trim() + "\n";
  return { markdown: out, warnings };
}
function convertYuqueBody(body) {
  if (!body || !body.trim()) return { markdown: "", warnings: [] };
  return isLakeBody(body) ? lakeToMarkdown(body) : cleanMarkdownBody(body);
}

// src/yuque/sync.ts
function sanitizeFileName(name) {
  let n = (name || "").replace(/[\\/:*?"<>|#^\[\]]/g, " ").replace(/\s+/g, " ").trim();
  if (!n) n = "\u672A\u547D\u540D\u6587\u6863";
  return n;
}
async function ensureFolder(app, folder) {
  const path = (0, import_obsidian4.normalizePath)(folder);
  if (!path || path === "/" || path === ".") return;
  const parts = path.split("/");
  let cur = "";
  for (const part of parts) {
    if (!part) continue;
    cur = cur ? `${cur}/${part}` : part;
    try {
      if (!await app.vault.adapter.exists(cur)) {
        await app.vault.adapter.mkdir(cur);
      }
    } catch (e) {
    }
  }
}
function joinPath(...parts) {
  return parts.filter((p) => p && p.trim() && p !== "/" && p !== ".").join("/");
}
function buildTocFolders(toc) {
  const byUuid = /* @__PURE__ */ new Map();
  for (const n of toc) byUuid.set(n.uuid, n);
  const slugToFolder = /* @__PURE__ */ new Map();
  for (const n of toc) {
    if (n.type !== "DOC" || !n.slug) continue;
    const segs = [];
    let cur = n;
    const guard = /* @__PURE__ */ new Set();
    while (cur && cur.parent_uuid && !guard.has(cur.parent_uuid)) {
      guard.add(cur.parent_uuid);
      const parent = byUuid.get(cur.parent_uuid);
      if (!parent) break;
      if (parent.type !== "DOC" && parent.title) segs.unshift(sanitizeFileName(parent.title));
      cur = parent;
    }
    slugToFolder.set(n.slug, segs.join("/"));
  }
  return slugToFolder;
}
function hashUrl(url) {
  let h = 5381;
  for (let i = 0; i < url.length; i++) h = (h << 5) + h + url.charCodeAt(i) >>> 0;
  return h.toString(36);
}
function imageExtFromUrl(url) {
  try {
    const m = decodeURIComponent(url).match(/\.(png|jpe?g|gif|webp|svg|bmp|ico)(?:[?#]|$)/i);
    if (m) {
      const ext = m[1].toLowerCase();
      return ext === "jpeg" ? "jpg" : ext;
    }
  } catch (e) {
  }
  return "png";
}
function buildFrontmatter(fields) {
  const lines = Object.entries(fields).filter(([, v]) => v).map(([k, v]) => `${k}: ${v.replace(/"/g, '\\"')}`);
  if (lines.length === 0) return "";
  return `---
${lines.join("\n")}
---
`;
}
async function syncTask(plugin, api, task, log) {
  var _a;
  const settings = plugin.settings;
  const ns = task.namespace;
  const retryLog = (waitSec, attempt) => log(`\u8BED\u96C0 API \u9650\u6D41\uFF0C${waitSec} \u79D2\u540E\u81EA\u52A8\u91CD\u8BD5\uFF08\u7B2C ${attempt} \u6B21\uFF09\u2026`);
  log(`\u6B63\u5728\u83B7\u53D6\u77E5\u8BC6\u5E93\u76EE\u5F55\u300C${task.repoName}\u300D\u2026`);
  let toc = await api.getToc(ns, retryLog);
  let docList = await api.getDocListOnce(ns);
  if (docList.length === 0 && toc.length > 0) {
    for (const node of toc) {
      const m = (_a = node.url) == null ? void 0 : _a.match(/^\/([^/]+)\/([^/]+)/);
      if (m && m[1] && m[1] !== ns) {
        const retry = await api.getDocListOnce(m[1]);
        if (retry.length > 0) {
          log(`\u6309 TOC \u4E2D\u7684 namespace\uFF08${m[1]}\uFF09\u91CD\u65B0\u83B7\u53D6\u6587\u6863\u5217\u8868\u6210\u529F\uFF1A${retry.length} \u7BC7`, "success");
          docList = retry;
        }
        break;
      }
    }
  }
  if (toc.length === 0 && docList.length === 0 && task.repoId) {
    log(`\u4EE5 namespace \u83B7\u53D6\u4E3A\u7A7A\uFF0C\u5C1D\u8BD5\u77E5\u8BC6\u5E93 ID\uFF08${task.repoId}\uFF09\u2026`);
    try {
      const tocById = await api.getToc(String(task.repoId), retryLog);
      const docsById = await api.getDocListOnce(String(task.repoId));
      if (tocById.length > 0 || docsById.length > 0) {
        toc = tocById;
        docList = docsById;
        log(`\u2713 ID \u8BBF\u95EE\u6210\u529F\uFF1A\u76EE\u5F55 ${toc.length} \u8282\u70B9\uFF0C\u6587\u6863\u5217\u8868 ${docList.length} \u7BC7`, "success");
      }
    } catch (e) {
      log(`ID \u8BBF\u95EE\u5931\u8D25\uFF1A${e.message}`, "error");
    }
  }
  const tocFolders = buildTocFolders(toc);
  log(`\u76EE\u5F55\uFF08TOC\uFF09\u8282\u70B9\u6570\uFF1A${toc.length}`);
  const docBySlug = /* @__PURE__ */ new Map();
  for (const d of docList) docBySlug.set(d.slug, d);
  if (docList.length === 0 && toc.length > 0) {
    const tocDocs = toc.filter((n) => n.type === "DOC" && n.slug).map((n) => ({
      id: 0,
      slug: n.slug,
      title: n.title,
      updated_at: ""
    }));
    if (tocDocs.length > 0) {
      log(`\u6587\u6863\u5217\u8868\u4E3A\u7A7A\uFF0C\u6539\u6309\u76EE\u5F55\u8282\u70B9\u540C\u6B65 ${tocDocs.length} \u7BC7\u6587\u6863\u2026`);
      for (const d of tocDocs) {
        if (!docBySlug.has(d.slug)) {
          docBySlug.set(d.slug, d);
          docList.push(d);
        }
      }
    }
  }
  if (docList.length === 0) {
    log(
      `\u26A0 \u76EE\u5F55\u4E0E\u6587\u6863\u5217\u8868\u5747\u4E3A\u7A7A\uFF1A\u300C${task.repoName}\u300D\u53EF\u80FD\u662F\u7A7A\u77E5\u8BC6\u5E93\uFF0C\u6216 Token \u65E0\u6743\u8BFB\u53D6\u5B83\u3002\u8BF7\u786E\u8BA4\u8BE5\u77E5\u8BC6\u5E93\u5728\u8BED\u96C0\u7F51\u9875\u4E2D\u786E\u5B9E\u6709\u6587\u6863\uFF0C\u4E14 Token \u52FE\u9009\u4E86\u8BFB\u53D6\u6743\u9650`,
      "error"
    );
  }
  let targets;
  if (task.mode === "selected") {
    targets = task.selectedDocs.map((sd) => docBySlug.get(sd.slug)).filter((d) => !!d);
    const missing = task.selectedDocs.filter((sd) => !docBySlug.has(sd.slug));
    if (missing.length > 0) log(`\u8B66\u544A\uFF1A${missing.length} \u7BC7\u6240\u9009\u6587\u6863\u5DF2\u4E0D\u5B58\u5728`, "error");
  } else {
    const tocOrder = /* @__PURE__ */ new Map();
    toc.forEach((n, i) => {
      if (n.slug && !tocOrder.has(n.slug)) tocOrder.set(n.slug, i);
    });
    const inToc = [];
    const notInToc = [];
    for (const d of docList) (tocOrder.has(d.slug) ? inToc : notInToc).push(d);
    inToc.sort((a, b) => {
      var _a2, _b;
      return ((_a2 = tocOrder.get(a.slug)) != null ? _a2 : 0) - ((_b = tocOrder.get(b.slug)) != null ? _b : 0);
    });
    targets = [...inToc, ...notInToc];
    if (notInToc.length > 0) log(`${notInToc.length} \u7BC7\u6587\u6863\u672A\u52A0\u5165\u8BED\u96C0\u76EE\u5F55\uFF0C\u6392\u5728\u6700\u540E`);
  }
  const state = settings.yuqueSyncState || {};
  const pending = [];
  let skipped = 0;
  for (const d of targets) {
    const key = `${ns}/${d.slug}`;
    const basePath = joinPath(
      task.targetFolder,
      tocFolders.get(d.slug) || "",
      sanitizeFileName(d.title)
    );
    const file = plugin.app.vault.getAbstractFileByPath(`${basePath}.md`);
    if (state[key] === d.updated_at && file instanceof import_obsidian4.TFile) {
      skipped++;
      continue;
    }
    pending.push(d);
  }
  log(`\u5171 ${targets.length} \u7BC7\uFF0C\u9700\u66F4\u65B0 ${pending.length} \u7BC7\uFF0C\u8DF3\u8FC7\u672A\u53D8\u5316 ${skipped} \u7BC7`);
  const staged = [];
  for (const d of pending) {
    try {
      const detail = await api.getDoc(ns, d.slug);
      const result = convertYuqueBody(detail.body || "");
      const folder = joinPath(task.targetFolder, tocFolders.get(d.slug) || "");
      const frontmatter = buildFrontmatter({
        title: detail.title,
        source: `https://www.yuque.com/${ns}/${d.slug}`,
        yuque_updated_at: detail.updated_at
      });
      staged.push({
        slug: d.slug,
        title: detail.title || d.title,
        basePath: joinPath(folder, sanitizeFileName(detail.title || d.title)),
        content: frontmatter + "\n" + result.markdown,
        updated_at: d.updated_at,
        warnings: result.warnings
      });
      for (const w of result.warnings) log(`  \u26A0 ${d.title}\uFF1A${w}`);
    } catch (e) {
      log(`\u62C9\u53D6\u5931\u8D25\u300C${d.title}\u300D\uFF1A${e.message}`, "error");
    }
  }
  if (staged.length === 0) {
    log("\u6CA1\u6709\u9700\u8981\u5199\u5165\u7684\u6587\u6863", "info");
    return;
  }
  const slugToTitle = /* @__PURE__ */ new Map();
  for (const t of targets) slugToTitle.set(t.slug, sanitizeFileName(t.title));
  for (const doc of staged) {
    doc.content = doc.content.replace(
      /\[([^\]]*)\]\(https?:\/\/(?:www\.)?yuque\.com\/([^)\s/]+)\/([^)\s/?"#]+)[^)]*\)/g,
      (full, text, linkNs, linkSlug) => {
        if (linkNs === ns && slugToTitle.has(linkSlug) && targets.some((t) => t.slug === linkSlug)) {
          const target = slugToTitle.get(linkSlug);
          return text && text !== target ? `[[${target}|${text}]]` : `[[${target}]]`;
        }
        return full;
      }
    );
  }
  if (settings.yuqueDownloadImages) {
    const assetsRoot = joinPath(task.targetFolder, settings.yuqueAssetsFolder || "assets");
    await ensureFolder(plugin.app, assetsRoot);
    let done = 0;
    for (const doc of staged) {
      const matches = Array.from(doc.content.matchAll(/!\[([^\]]*)\]\((https?:\/\/[^)\s]+)\)/g));
      for (const m of matches) {
        const [full, alt, url] = m;
        if (!/yuque|nlark|alicdn/.test(url)) continue;
        const ext = imageExtFromUrl(url);
        const fileName = `yuque-${hashUrl(url)}.${ext}`;
        const assetPath = `${assetsRoot}/${fileName}`;
        try {
          if (!await plugin.app.vault.adapter.exists(assetPath)) {
            const buf = await api.downloadBinary(url);
            await plugin.app.vault.adapter.writeBinary(assetPath, buf);
          }
          const docFolder = doc.basePath.includes("/") ? doc.basePath.slice(0, doc.basePath.lastIndexOf("/")) : "";
          let rel = (0, import_obsidian4.normalizePath)(assetsRoot);
          if (docFolder) {
            const up = docFolder.split("/").length;
            rel = "../".repeat(up) + assetsRoot;
          }
          rel = (0, import_obsidian4.normalizePath)(rel) + "/" + fileName;
          doc.content = doc.content.split(full).join(`![${alt}](${rel})`);
          done++;
        } catch (e) {
          log(`  \u26A0 \u56FE\u7247\u4E0B\u8F7D\u5931\u8D25\uFF08\u4FDD\u7559\u8FDC\u7A0B\u94FE\u63A5\uFF09\uFF1A${e.message}`, "error");
        }
      }
    }
    if (done > 0) log(`\u5DF2\u672C\u5730\u5316 ${done} \u5F20\u56FE\u7247 \u2192 ${assetsRoot}/`);
  }
  let written = 0;
  for (const doc of staged) {
    const filePath = `${doc.basePath}.md`;
    try {
      if (doc.basePath.includes("/")) {
        await ensureFolder(plugin.app, doc.basePath.slice(0, doc.basePath.lastIndexOf("/")));
      }
      const existing = plugin.app.vault.getAbstractFileByPath(filePath);
      if (existing instanceof import_obsidian4.TFile) {
        await plugin.app.vault.modify(existing, doc.content);
      } else {
        await plugin.app.vault.create(filePath, doc.content);
      }
      state[`${ns}/${doc.slug}`] = doc.updated_at;
      written++;
    } catch (e) {
      log(`\u5199\u5165\u5931\u8D25\u300C${doc.title}\u300D\uFF1A${e.message}`, "error");
    }
  }
  settings.yuqueSyncState = state;
  await plugin.saveSettings();
  log(`\u300C${task.repoName}\u300D\u5B8C\u6210\uFF1A\u5199\u5165/\u66F4\u65B0 ${written} \u7BC7`, "success");
  if (toc.length > 0 && task.mode === "all") {
    try {
      const slugToTitle2 = /* @__PURE__ */ new Map();
      for (const t of targets) slugToTitle2.set(t.slug, sanitizeFileName(t.title));
      const byUuid = /* @__PURE__ */ new Map();
      for (const n of toc) byUuid.set(n.uuid, n);
      const lines = [`# ${task.repoName} \xB7 \u77E5\u8BC6\u5E93\u76EE\u5F55`, ""];
      for (const n of toc) {
        let depth = 0;
        let cur = n;
        const guard = /* @__PURE__ */ new Set();
        while ((cur == null ? void 0 : cur.parent_uuid) && !guard.has(cur.parent_uuid)) {
          guard.add(cur.parent_uuid);
          cur = byUuid.get(cur.parent_uuid);
          depth++;
        }
        const indent = "  ".repeat(depth);
        if (n.type === "DOC" && n.slug && slugToTitle2.has(n.slug)) {
          lines.push(`${indent}- [[${slugToTitle2.get(n.slug)}|${n.title}]]`);
        } else if (n.title) {
          lines.push(`${indent}- **${n.title}**`);
        }
      }
      const indexContent = buildFrontmatter({
        title: `${task.repoName} \u77E5\u8BC6\u5E93\u76EE\u5F55`,
        source: `https://www.yuque.com/${ns}`
      }) + `
${lines.join("\n")}
`;
      const indexPath = joinPath(task.targetFolder, `${sanitizeFileName(task.repoName)} \u76EE\u5F55.md`);
      if (indexPath.includes("/")) {
        await ensureFolder(plugin.app, indexPath.slice(0, indexPath.lastIndexOf("/")));
      }
      const existingIndex = plugin.app.vault.getAbstractFileByPath(indexPath);
      if (existingIndex instanceof import_obsidian4.TFile) {
        await plugin.app.vault.modify(existingIndex, indexContent);
      } else {
        await plugin.app.vault.create(indexPath, indexContent);
      }
      log(`\u5DF2\u66F4\u65B0\u77E5\u8BC6\u5E93\u76EE\u5F55\u7D22\u5F15\uFF1A${indexPath}`, "success");
    } catch (e) {
      log(`\u76EE\u5F55\u7D22\u5F15\u751F\u6210\u5931\u8D25\uFF1A${e.message}`, "error");
    }
  }
}
async function syncAllTasks(plugin, log) {
  const settings = plugin.settings;
  if (!settings.yuqueToken) {
    log("\u8BF7\u5148\u5728\u63D2\u4EF6\u8BBE\u7F6E\u4E2D\u586B\u5199\u8BED\u96C0 Token", "error");
    return;
  }
  if (!settings.yuqueTasks || settings.yuqueTasks.length === 0) {
    log("\u8FD8\u6CA1\u6709\u540C\u6B65\u4EFB\u52A1\uFF0C\u8BF7\u5148\u5728\u8BBE\u7F6E\u6216\u7528\u300C\u6DFB\u52A0\u8BED\u96C0\u540C\u6B65\u4EFB\u52A1\u300D\u547D\u4EE4\u521B\u5EFA", "error");
    return;
  }
  const api = new YuqueApi(settings.yuqueToken);
  for (const task of settings.yuqueTasks) {
    try {
      await syncTask(plugin, api, task, log);
    } catch (e) {
      log(`\u4EFB\u52A1\u300C${task.repoName}\u300D\u5931\u8D25\uFF1A${e.message}`, "error");
    }
  }
}

// src/yuque/ui.ts
var import_obsidian5 = require("obsidian");
var SyncModal = class extends import_obsidian5.Modal {
  constructor(app, title) {
    super(app);
    this.title = title;
  }
  onOpen() {
    this.titleEl.setText(this.title);
    this.contentEl.empty();
    this.logEl = this.contentEl.createDiv({ cls: "yuque-sync-log" });
    this.modalEl.addClass("yuque-sync-modal");
  }
  log(msg, type = "info") {
    if (!this.logEl) return;
    const line = this.logEl.createDiv({ cls: `yuque-sync-log-line yuque-sync-${type}` });
    line.setText(`[${(/* @__PURE__ */ new Date()).toLocaleTimeString()}] ${msg}`);
    this.logEl.scrollTop = this.logEl.scrollHeight;
  }
  onClose() {
    this.contentEl.empty();
  }
};
async function runWithSyncModal(plugin, title, fn) {
  const modal = new SyncModal(plugin.app, title);
  modal.open();
  const log = (msg, type) => modal.log(msg, type);
  try {
    await fn(log, modal);
  } catch (e) {
    console.error("[yuque-style] \u540C\u6B65\u51FA\u9519", e);
    log(`\u51FA\u9519\uFF1A${e.message}`, "error");
  } finally {
    log("\u2014\u2014 \u7ED3\u675F \u2014\u2014");
  }
}
var AddTaskModal = class extends import_obsidian5.Modal {
  constructor(plugin, onConfirm) {
    super(plugin.app);
    this.plugin = plugin;
    this.onConfirm = onConfirm;
    this.repos = [];
    this.repoIdx = 0;
    this.mode = "all";
    this.targetFolder = "";
    this.docList = [];
    this.checkedDocs = /* @__PURE__ */ new Set();
    this.confirmBtn = null;
    this.docSectionEl = null;
  }
  onOpen() {
    this.titleEl.setText("\u6DFB\u52A0\u8BED\u96C0\u540C\u6B65\u4EFB\u52A1");
    this.contentEl.empty();
    this.bodyEl = this.contentEl.createDiv();
    const loading = this.bodyEl.createEl("p", { text: "\u6B63\u5728\u83B7\u53D6\u77E5\u8BC6\u5E93\u5217\u8868\u2026" });
    new import_obsidian5.Setting(this.contentEl).addButton((b) => {
      this.confirmBtn = b.buttonEl;
      b.setButtonText("\u521B\u5EFA\u5E76\u540C\u6B65").setCta().onClick(async () => {
        const task = await this.buildTask();
        if (!task) return;
        this.onConfirm(task);
        this.close();
      });
      b.buttonEl.disabled = true;
      b.buttonEl.style.opacity = "0.5";
    });
    void this.loadRepos(loading);
  }
  async loadRepos(loadingEl) {
    try {
      const api = new YuqueApi(this.plugin.settings.yuqueToken);
      this.repos = await api.getRepos();
    } catch (e) {
      console.error("[yuque-style] \u83B7\u53D6\u77E5\u8BC6\u5E93\u5931\u8D25", e);
      loadingEl.setText(`\u83B7\u53D6\u77E5\u8BC6\u5E93\u5931\u8D25\uFF1A${e.message}`);
      return;
    }
    if (this.repos.length === 0) {
      loadingEl.setText("\u8BE5 Token \u4E0B\u6CA1\u6709\u53EF\u8BBF\u95EE\u7684\u77E5\u8BC6\u5E93");
      return;
    }
    loadingEl.remove();
    this.renderForm();
  }
  renderForm() {
    var _a;
    const s = this.plugin.settings;
    this.bodyEl.empty();
    new import_obsidian5.Setting(this.bodyEl).setName("\u77E5\u8BC6\u5E93").setDesc("\u9009\u62E9\u8981\u540C\u6B65\u7684\u8BED\u96C0\u77E5\u8BC6\u5E93").addDropdown((d) => {
      for (const r of this.repos) d.addOption(String(this.repos.indexOf(r)), r.name);
      d.setValue("0").onChange(async (v) => {
        var _a2;
        this.repoIdx = Number(v);
        this.docList = [];
        this.checkedDocs.clear();
        this.mode = "all";
        this.targetFolder = ((_a2 = this.repos[this.repoIdx]) == null ? void 0 : _a2.name) || "";
        this.renderForm();
      });
    });
    const rangeSetting = new import_obsidian5.Setting(this.bodyEl).setName("\u540C\u6B65\u8303\u56F4").setDesc("\u6574\u4E2A\u77E5\u8BC6\u5E93 \u6216 \u53EA\u540C\u6B65\u52FE\u9009\u7684\u6587\u6863");
    rangeSetting.addDropdown((d) => {
      d.addOption("all", "\u6574\u4E2A\u77E5\u8BC6\u5E93");
      d.addOption("selected", "\u9009\u62E9\u6587\u6863");
      d.setValue(this.mode).onChange(async (v) => {
        this.mode = v;
        if (this.mode === "selected" && this.docList.length === 0) {
          try {
            new import_obsidian5.Notice("\u6B63\u5728\u83B7\u53D6\u6587\u6863\u5217\u8868\u2026");
            const api = new YuqueApi(this.plugin.settings.yuqueToken);
            this.docList = await api.getDocList(this.repos[this.repoIdx].namespace);
          } catch (e) {
            new import_obsidian5.Notice(`\u83B7\u53D6\u6587\u6863\u5217\u8868\u5931\u8D25\uFF1A${e.message}`);
            this.mode = "all";
            this.renderForm();
            return;
          }
        }
        this.renderForm();
      });
    });
    if (this.docSectionEl) this.docSectionEl.remove();
    this.docSectionEl = null;
    if (this.mode === "selected") {
      const section = this.bodyEl.createDiv();
      this.docSectionEl = section;
      if (this.docList.length === 0) {
        section.createEl("p", { text: "\u8BE5\u77E5\u8BC6\u5E93\u6CA1\u6709\u6587\u6863" });
      } else {
        section.createEl("p", {
          text: `\u52FE\u9009\u8981\u540C\u6B65\u7684\u6587\u6863\uFF08\u5DF2\u9009 ${this.checkedDocs.size}/${this.docList.length} \u7BC7\uFF09\uFF1A`,
          cls: "setting-item-description"
        });
        const listEl = section.createDiv({ cls: "yuque-doc-select-list" });
        for (const doc of this.docList) {
          const row = listEl.createDiv({ cls: "yuque-doc-select-row" });
          const cb = row.createEl("input", { type: "checkbox" });
          cb.checked = this.checkedDocs.has(doc.slug);
          cb.addEventListener("change", () => {
            if (cb.checked) this.checkedDocs.add(doc.slug);
            else this.checkedDocs.delete(doc.slug);
            const p = section.querySelector("p.setting-item-description");
            if (p)
              p.setText(
                `\u52FE\u9009\u8981\u540C\u6B65\u7684\u6587\u6863\uFF08\u5DF2\u9009 ${this.checkedDocs.size}/${this.docList.length} \u7BC7\uFF09\uFF1A`
              );
          });
          row.createSpan({ text: doc.title });
        }
        new import_obsidian5.Setting(section).addButton(
          (b) => b.setButtonText("\u5168\u9009").onClick(() => {
            listEl.querySelectorAll("input[type=checkbox]").forEach((el) => el.checked = true);
            this.docList.forEach((d) => this.checkedDocs.add(d.slug));
            const p = section.querySelector("p.setting-item-description");
            if (p)
              p.setText(
                `\u52FE\u9009\u8981\u540C\u6B65\u7684\u6587\u6863\uFF08\u5DF2\u9009 ${this.checkedDocs.size}/${this.docList.length} \u7BC7\uFF09\uFF1A`
              );
          })
        );
      }
    }
    if (!this.targetFolder) this.targetFolder = ((_a = this.repos[this.repoIdx]) == null ? void 0 : _a.name) || "";
    const folderSetting = new import_obsidian5.Setting(this.bodyEl).setName("\u76EE\u6807\u6587\u4EF6\u5939").setDesc("\u540C\u6B65\u5230\u4ED3\u5E93\u4E2D\u7684\u8DEF\u5F84\uFF0C\u7559\u7A7A = \u6839\u76EE\u5F55\uFF1B\u6587\u6863\u4F1A\u6309\u8BED\u96C0\u76EE\u5F55\u7ED3\u6784\u5B58\u653E");
    const text = new import_obsidian5.TextComponent(folderSetting.controlEl);
    text.setPlaceholder("\u7559\u7A7A = \u4ED3\u5E93\u6839\u76EE\u5F55");
    text.setValue(this.targetFolder);
    text.inputEl.addClass("yuque-folder-input");
    text.onChange((v) => this.targetFolder = v);
    if (this.confirmBtn) {
      this.confirmBtn.disabled = false;
      this.confirmBtn.style.opacity = "1";
    }
  }
  async buildTask() {
    const repo = this.repos[this.repoIdx];
    if (!repo) return null;
    let selectedDocs = [];
    if (this.mode === "selected") {
      selectedDocs = this.docList.filter((d) => this.checkedDocs.has(d.slug));
      if (selectedDocs.length === 0) {
        new import_obsidian5.Notice("\u672A\u52FE\u9009\u4EFB\u4F55\u6587\u6863");
        return null;
      }
    }
    return {
      repoId: repo.id,
      namespace: repo.namespace,
      repoName: repo.name,
      targetFolder: this.targetFolder.trim(),
      mode: this.mode,
      selectedDocs
    };
  }
  onClose() {
    this.bodyEl.empty();
  }
};
async function addSyncTaskFlow(plugin) {
  if (!plugin.settings.yuqueToken) {
    new import_obsidian5.Notice("\u8BF7\u5148\u5728\u63D2\u4EF6\u8BBE\u7F6E\u4E2D\u586B\u5199\u8BED\u96C0 Token");
    return;
  }
  const task = await new Promise((resolve) => {
    let settled = false;
    const modal = new AddTaskModal(plugin, (t) => {
      if (!settled) {
        settled = true;
        resolve(t);
      }
    });
    const origOnClose = modal.onClose.bind(modal);
    modal.onClose = () => {
      origOnClose();
      if (!settled) {
        settled = true;
        resolve(null);
      }
    };
    modal.open();
  });
  if (!task) return;
  const settings = plugin.settings;
  const others = (settings.yuqueTasks || []).filter((t) => t.namespace !== task.namespace);
  settings.yuqueTasks = [...others, task];
  await plugin.saveSettings();
  await new Promise((r) => setTimeout(r, 200));
  await runWithSyncModal(plugin, `\u540C\u6B65\u300C${task.repoName}\u300D`, async (log) => {
    await syncTask(plugin, new YuqueApi(settings.yuqueToken), task, log);
  });
}
async function syncAllFlow(plugin) {
  const tasks = plugin.settings.yuqueTasks || [];
  if (tasks.length === 0) {
    const go = await new Promise((resolve) => {
      let settled = false;
      const modal = new import_obsidian5.Modal(plugin.app);
      modal.titleEl.setText("\u8BED\u96C0\u540C\u6B65");
      modal.contentEl.createEl("p", {
        text: "\u8FD8\u6CA1\u6709\u540C\u6B65\u4EFB\u52A1\u3002\u662F\u5426\u73B0\u5728\u521B\u5EFA\u4E00\u4E2A\uFF1F\uFF08\u9009\u62E9\u77E5\u8BC6\u5E93\u3001\u8303\u56F4\u4E0E\u76EE\u6807\u6587\u4EF6\u5939\uFF09"
      });
      new import_obsidian5.Setting(modal.contentEl).addButton(
        (b) => b.setButtonText("\u521B\u5EFA\u540C\u6B65\u4EFB\u52A1").setCta().onClick(() => {
          if (!settled) {
            settled = true;
            resolve(true);
          }
          modal.close();
        })
      );
      modal.onClose = () => {
        if (!settled) {
          settled = true;
          resolve(false);
        }
      };
      modal.open();
    });
    if (!go) return;
    await new Promise((r) => setTimeout(r, 200));
    await addSyncTaskFlow(plugin);
    return;
  }
  await runWithSyncModal(plugin, "\u8BED\u96C0\u540C\u6B65", async (log) => {
    await syncAllTasks(plugin, log);
  });
}
function safeJson(text) {
  try {
    return JSON.parse(text);
  } catch (e) {
    return null;
  }
}
async function diagnoseFlow(plugin) {
  if (!plugin.settings.yuqueToken) {
    new import_obsidian5.Notice("\u8BF7\u5148\u5728\u63D2\u4EF6\u8BBE\u7F6E\u4E2D\u586B\u5199\u8BED\u96C0 Token");
    return;
  }
  await runWithSyncModal(plugin, "\u8BED\u96C0\u540C\u6B65\u8BCA\u65AD", async (log) => {
    var _a, _b, _c, _d;
    const api = new YuqueApi(plugin.settings.yuqueToken);
    const userRes = await api.getRaw("/user");
    const user = (_a = safeJson(userRes.text)) == null ? void 0 : _a.data;
    const login = user == null ? void 0 : user.login;
    log(`GET /user \u2192 ${userRes.status}\uFF0C\u7528\u6237\uFF1A${(_b = user == null ? void 0 : user.name) != null ? _b : "?"}\uFF08login: ${login != null ? login : "?"}\uFF09`);
    if (userRes.status !== 200) {
      log(`  \u54CD\u5E94\uFF1A${userRes.text.slice(0, 200)}`, "error");
      return;
    }
    const reposRes = await api.getRaw(
      `/users/${encodeURIComponent(String(login))}/repos?offset=0&limit=100`
    );
    const reposData = (_c = safeJson(reposRes.text)) == null ? void 0 : _c.data;
    const repos = Array.isArray(reposData) ? reposData : [];
    log(`GET /users/${login}/repos \u2192 ${reposRes.status}\uFF0C${repos.length} \u4E2A\u77E5\u8BC6\u5E93`);
    for (const r of repos.slice(0, 30)) {
      log(`  \xB7 ${r.name}\uFF08namespace: ${r.namespace}\uFF0Cid: ${r.id}\uFF09`);
    }
    const tasks = plugin.settings.yuqueTasks || [];
    if (tasks.length === 0) {
      log("\u6CA1\u6709\u540C\u6B65\u4EFB\u52A1\uFF0C\u4EC5\u5217\u51FA\u77E5\u8BC6\u5E93\u4FE1\u606F\u3002\u53EF\u5728\u4E0A\u65B9 namespace \u4E2D\u9009\u4E00\u4E2A\u624B\u52A8\u8BCA\u65AD", "info");
    }
    for (const task of tasks) {
      const probes = [
        ["\u76EE\u5F55 by namespace", `/repos/${nsPath(task.namespace)}/toc`],
        ["\u76EE\u5F55 by id", `/repos/${task.repoId}/toc`],
        ["\u6587\u6863\u5217\u8868 by namespace", `/repos/${nsPath(task.namespace)}/docs?offset=0&limit=100`],
        ["\u6587\u6863\u5217\u8868 by id", `/repos/${task.repoId}/docs?offset=0&limit=100`]
      ];
      for (const [label, path] of probes) {
        const r = await api.getRaw(path);
        const data = (_d = safeJson(r.text)) == null ? void 0 : _d.data;
        const count = Array.isArray(data) ? `${data.length} \u9879` : `\u975E\u6570\u7EC4\uFF08${data === null ? "null" : typeof data}\uFF09`;
        log(`\u300C${task.repoName}\u300D${label} \u2192 ${r.status}\uFF0C${count}`);
        console.log(`[yuque-style \u8BCA\u65AD] ${label} ${path}
  status=${r.status}
  ${r.text.slice(0, 3e3)}`);
        if (r.status !== 200) log(`  \u54CD\u5E94\uFF1A${r.text.slice(0, 200)}`, "error");
      }
    }
    log("\u2014\u2014 \u5B8C\u6574\u539F\u59CB\u54CD\u5E94\u5DF2\u6253\u5370\u5230\u63A7\u5236\u53F0\uFF08Ctrl+Shift+I \u2192 Console\uFF09\u2014\u2014");
  });
}

// src/main.ts
var DEFAULT_SETTINGS = {
  toolbar: true,
  slashMenu: true,
  reader: true,
  showDocHeader: true,
  showOutline: false,
  showReadingTime: true,
  contentWidth: 820,
  headingNumbers: true,
  yuqueToken: "",
  yuqueTasks: [],
  yuqueDownloadImages: true,
  yuqueAssetsFolder: "assets",
  yuqueSyncState: {}
};
var YuqueStylePlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
  }
  async onload() {
    await this.loadSettings();
    console.log(`[yuque-style] loaded v${this.manifest.version}`);
    this.registerEditorExtension(buildYuqueToolbar(() => this.settings.toolbar));
    this.registerEditorSuggest(new YuqueSlashSuggest(this));
    this.reader = new ReaderEnhancer(this);
    this.reader.register();
    this.applyCssVars();
    this.addSettingTab(new YuqueSettingTab(this));
    this.addCommand({
      id: "insert-callout",
      name: "\u63D2\u5165\u5361\u7247\u5757\uFF08\u8BED\u96C0\u6807\u6CE8\uFF09",
      editorCallback: (editor) => {
        editor.replaceSelection("> [!note] \u5361\u7247\u6807\u9898\n> \u5728\u8FD9\u91CC\u586B\u5199\u5361\u7247\u5185\u5BB9\u3002\n\n");
      }
    });
    this.addCommand({
      id: "insert-todo",
      name: "\u63D2\u5165\u5F85\u529E\u6E05\u5355",
      editorCallback: (editor) => {
        editor.replaceSelection(
          "- [ ] \u5F85\u529E\u4E8B\u9879\u4E00\n- [ ] \u5F85\u529E\u4E8B\u9879\u4E8C\n- [ ] \u5F85\u529E\u4E8B\u9879\u4E09\n"
        );
      }
    });
    this.addCommand({
      id: "insert-table",
      name: "\u63D2\u5165\u8868\u683C",
      editorCallback: (editor) => {
        editor.replaceSelection(
          "| \u5217\u540D | \u5217\u540D | \u5217\u540D |\n| --- | --- | --- |\n| \u5185\u5BB9 | \u5185\u5BB9 | \u5185\u5BB9 |\n| \u5185\u5BB9 | \u5185\u5BB9 | \u5185\u5BB9 |\n"
        );
      }
    });
    this.addCommand({
      id: "toggle-outline",
      name: "\u663E\u793A / \u9690\u85CF\u6587\u6863\u76EE\u5F55",
      callback: () => this.reader.toggleOutline()
    });
    this.addCommand({
      id: "toggle-reader-enhance",
      name: "\u5F00\u542F / \u5173\u95ED\u9605\u8BFB\u589E\u5F3A",
      callback: async () => {
        this.settings.reader = !this.settings.reader;
        await this.saveSettings();
        this.reader.refresh(true);
        new import_obsidian6.Notice(this.settings.reader ? "\u9605\u8BFB\u589E\u5F3A\u5DF2\u5F00\u542F" : "\u9605\u8BFB\u589E\u5F3A\u5DF2\u5173\u95ED");
      }
    });
    this.addRibbonIcon("refresh-cw", "\u540C\u6B65\u8BED\u96C0\u6587\u6863", () => syncAllFlow(this));
    this.addCommand({
      id: "yuque-sync-all",
      name: "\u8BED\u96C0\u540C\u6B65\uFF1A\u7ACB\u5373\u540C\u6B65\u5168\u90E8\u4EFB\u52A1",
      callback: () => syncAllFlow(this)
    });
    this.addCommand({
      id: "yuque-sync-add",
      name: "\u8BED\u96C0\u540C\u6B65\uFF1A\u6DFB\u52A0/\u66F4\u65B0\u540C\u6B65\u4EFB\u52A1\uFF08\u9009\u77E5\u8BC6\u5E93\u3001\u6587\u6863\u4E0E\u76EE\u6807\u8DEF\u5F84\uFF09",
      callback: () => addSyncTaskFlow(this)
    });
    this.addCommand({
      id: "yuque-diagnose",
      name: "\u8BED\u96C0\u540C\u6B65\uFF1A\u8BCA\u65AD\uFF08\u6392\u67E5\u62C9\u53D6\u4E3A\u7A7A\u7B49\u95EE\u9898\uFF09",
      callback: () => diagnoseFlow(this)
    });
  }
  onunload() {
    document.querySelectorAll(".yuque-doc-header, .yuque-outline").forEach((n) => n.remove());
    document.querySelectorAll(".yuque-reader").forEach((n) => n.classList.remove("yuque-reader"));
    document.documentElement.style.removeProperty("--yuque-content-width");
  }
  applyCssVars() {
    document.documentElement.style.setProperty(
      "--yuque-content-width",
      `${this.settings.contentWidth}px`
    );
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.applyCssVars();
  }
};
var YuqueSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(plugin) {
    super(plugin.app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const s = this.plugin.settings;
    containerEl.createEl("h2", { text: "\u8BED\u96C0\u98CE\u683C\u7F16\u8F91\u4E0E\u9605\u8BFB" });
    new import_obsidian6.Setting(containerEl).setName("\u60AC\u6D6E\u683C\u5F0F\u5DE5\u5177\u680F").setDesc("\u7F16\u8F91\u5668\u4E2D\u9009\u4E2D\u6587\u672C\u65F6\uFF0C\u5728\u9009\u533A\u4E0A\u65B9\u5F39\u51FA\u8BED\u96C0\u5F0F\u683C\u5F0F\u5DE5\u5177\u680F").addToggle(
      (t) => t.setValue(s.toolbar).onChange(async (v) => {
        s.toolbar = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u659C\u6760\u5FEB\u6377\u83DC\u5355").setDesc('\u7F16\u8F91\u65F6\u8F93\u5165 "/" \u5F39\u51FA\u8BED\u96C0\u5F0F\u5757\u63D2\u5165\u83DC\u5355\uFF08\u6807\u9898 / \u5361\u7247 / \u5F85\u529E / \u8868\u683C\u7B49\uFF09').addToggle(
      (t) => t.setValue(s.slashMenu).onChange(async (v) => {
        s.slashMenu = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u9605\u8BFB\u589E\u5F3A").setDesc("\u9605\u8BFB\u6A21\u5F0F\u4E0B\u542F\u7528\u6587\u6863\u5934\u3001\u76EE\u5F55\u4E0E\u8BED\u96C0\u5F0F\u6392\u7248").addToggle(
      (t) => t.setValue(s.reader).onChange(async (v) => {
        s.reader = v;
        await this.plugin.saveSettings();
        this.plugin.reader.refresh(true);
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u6587\u6863\u5934\u4FE1\u606F").setDesc("\u5728\u6587\u6863\u9876\u90E8\u5C55\u793A\u6807\u9898\u3001\u5B57\u6570\u3001\u9605\u8BFB\u65F6\u957F\u3001\u521B\u5EFA\u65E5\u671F\u4E0E\u6807\u7B7E").addToggle(
      (t) => t.setValue(s.showDocHeader).onChange(async (v) => {
        s.showDocHeader = v;
        await this.plugin.saveSettings();
        this.plugin.reader.refresh(true);
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u9884\u8BA1\u9605\u8BFB\u65F6\u957F").setDesc("\u6309\u6BCF\u5206\u949F 400 \u5B57\u4F30\u7B97").addToggle(
      (t) => t.setValue(s.showReadingTime).onChange(async (v) => {
        s.showReadingTime = v;
        await this.plugin.saveSettings();
        this.plugin.reader.refresh(true);
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u6D6E\u52A8\u76EE\u5F55").setDesc("\u9605\u8BFB\u6A21\u5F0F\u4E0B\u5728\u53F3\u4FA7\u663E\u793A\u672C\u6587\u76EE\u5F55\u5361\u7247").addToggle(
      (t) => t.setValue(s.showOutline).onChange(async (v) => {
        s.showOutline = v;
        await this.plugin.saveSettings();
        this.plugin.reader.refresh(true);
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u6807\u9898\u81EA\u52A8\u7F16\u53F7").setDesc("\u9605\u8BFB\u6A21\u5F0F\u4E0B\u4E3A\u6807\u9898\u663E\u793A\u5C42\u7EA7\u6570\u5B57\u7F16\u53F7\uFF081 / 1.1 / 1.1.1\uFF09\uFF1B\u6587\u6863\u81EA\u5E26\u7684\u7F16\u53F7\u4E0D\u53D7\u5F71\u54CD").addToggle(
      (t) => t.setValue(s.headingNumbers).onChange(async (v) => {
        s.headingNumbers = v;
        await this.plugin.saveSettings();
        this.plugin.reader.refresh(true);
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u6B63\u6587\u680F\u5BBD").setDesc("\u9605\u8BFB\u6A21\u5F0F\u4E0B\u6B63\u6587\u5185\u5BB9\u5BBD\u5EA6\uFF08\u50CF\u7D20\uFF09").addSlider(
      (sl) => sl.setLimits(600, 1100, 20).setValue(s.contentWidth).setDynamicTooltip().onChange(async (v) => {
        s.contentWidth = v;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "\u8BED\u96C0\u6587\u6863\u540C\u6B65" });
    new import_obsidian6.Setting(containerEl).setName("\u8BED\u96C0 Token").setDesc("\u5728\u8BED\u96C0\u7F51\u9875\u300C\u8D26\u53F7\u8BBE\u7F6E \u2192 \u5F00\u53D1\u8005 \u2192 Token\u300D\u521B\u5EFA\uFF0C\u9700\u8981\u300C\u8BFB\u53D6\u77E5\u8BC6\u5E93\u3001\u6587\u6863\u300D\u6743\u9650").addText((t) => {
      t.inputEl.type = "password";
      t.setPlaceholder("\u586B\u5165\u8BED\u96C0 Token").setValue(s.yuqueToken).onChange(async (v) => {
        s.yuqueToken = v.trim();
        await this.plugin.saveSettings();
      });
    }).addButton(
      (b) => b.setButtonText("\u6D4B\u8BD5\u8FDE\u63A5").onClick(async () => {
        var _a, _b;
        if (!s.yuqueToken) {
          new import_obsidian6.Notice("\u8BF7\u5148\u586B\u5199 Token");
          return;
        }
        b.setDisabled(true);
        try {
          const user = await new YuqueApi(s.yuqueToken).getUser();
          new import_obsidian6.Notice(`\u8FDE\u63A5\u6210\u529F\uFF1A${(_b = (_a = user == null ? void 0 : user.name) != null ? _a : user == null ? void 0 : user.login) != null ? _b : "\u5DF2\u8BA4\u8BC1"}`);
        } catch (e) {
          new import_obsidian6.Notice(`\u8FDE\u63A5\u5931\u8D25\uFF1A${e.message}`);
        } finally {
          b.setDisabled(false);
        }
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u540C\u6B65\u4EFB\u52A1").setDesc("\u6BCF\u4E2A\u4EFB\u52A1\u53EF\u9009\u62E9\u76EE\u6807\u6587\u4EF6\u5939\uFF1B\u540C\u6B65\u65F6\u6309\u8BED\u96C0\u66F4\u65B0\u65F6\u95F4\u589E\u91CF\u62C9\u53D6").addButton(
      (b) => b.setButtonText("\u6DFB\u52A0\u4EFB\u52A1").setCta().onClick(() => {
        addSyncTaskFlow(this.plugin);
      })
    );
    if (!s.yuqueTasks || s.yuqueTasks.length === 0) {
      containerEl.createEl("p", {
        text: "\u8FD8\u6CA1\u6709\u540C\u6B65\u4EFB\u52A1\u3002\u70B9\u51FB\u300C\u6DFB\u52A0\u4EFB\u52A1\u300D\uFF0C\u6216\u4F7F\u7528\u547D\u4EE4\u300C\u8BED\u96C0\u540C\u6B65\uFF1A\u6DFB\u52A0/\u66F4\u65B0\u540C\u6B65\u4EFB\u52A1\u300D\u3002",
        cls: "setting-item-description"
      });
    } else {
      for (const task of s.yuqueTasks) {
        const desc = task.mode === "all" ? "\u6574\u4E2A\u77E5\u8BC6\u5E93" : `\u6307\u5B9A\u6587\u6863 ${task.selectedDocs.length} \u7BC7`;
        const taskSetting = new import_obsidian6.Setting(containerEl).setName(task.repoName).setDesc(
          `${task.namespace} \xB7 ${desc} \xB7 \u76EE\u6807\uFF1A${task.targetFolder || "\u4ED3\u5E93\u6839\u76EE\u5F55"}`
        );
        taskSetting.addButton(
          (b) => b.setButtonText("\u7ACB\u5373\u540C\u6B65").onClick(() => {
            runWithSyncModal(this.plugin, `\u540C\u6B65\u300C${task.repoName}\u300D`, async (log) => {
              await syncTask(this.plugin, new YuqueApi(s.yuqueToken), task, log);
            });
          })
        );
        taskSetting.addButton(
          (b) => b.setButtonText("\u5220\u9664").onClick(async () => {
            s.yuqueTasks = s.yuqueTasks.filter((t) => t !== task);
            await this.plugin.saveSettings();
            this.display();
          })
        );
      }
    }
    new import_obsidian6.Setting(containerEl).setName("\u56FE\u7247\u672C\u5730\u5316").setDesc("\u540C\u6B65\u65F6\u628A\u8BED\u96C0 CDN \u56FE\u7247\u4E0B\u8F7D\u5230\u4ED3\u5E93\u5185\uFF0C\u907F\u514D\u5916\u94FE\u5931\u6548").addToggle(
      (t) => t.setValue(s.yuqueDownloadImages).onChange(async (v) => {
        s.yuqueDownloadImages = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u56FE\u7247\u5B58\u653E\u6587\u4EF6\u5939").setDesc("\u4F4D\u4E8E\u6BCF\u4E2A\u540C\u6B65\u4EFB\u52A1\u7684\u76EE\u6807\u6587\u4EF6\u5939\u4E4B\u4E0B").addText(
      (t) => t.setPlaceholder("assets").setValue(s.yuqueAssetsFolder).onChange(async (v) => {
        s.yuqueAssetsFolder = v.trim() || "assets";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("\u6E05\u9664\u589E\u91CF\u540C\u6B65\u8BB0\u5F55").setDesc("\u4E0B\u6B21\u540C\u6B65\u5C06\u5F3A\u5236\u91CD\u65B0\u62C9\u53D6\u5168\u90E8\u6587\u6863\uFF08\u672C\u5730\u6587\u4EF6\u4E0D\u4F1A\u88AB\u5220\u9664\uFF09").addButton(
      (b) => b.setButtonText("\u6E05\u9664").onClick(async () => {
        s.yuqueSyncState = {};
        await this.plugin.saveSettings();
        new import_obsidian6.Notice("\u5DF2\u6E05\u9664\u540C\u6B65\u8BB0\u5F55\uFF0C\u4E0B\u6B21\u5C06\u5168\u91CF\u62C9\u53D6");
      })
    );
  }
};
